// List of silly
var phrases = ["'Brexit wasn't enough, Buckingham should be separate from UK' -says angry man",
    "Student eats artwork of a banana duct-taped to a museum wall because 'he was hungry'",
    "'Man fixes Twisted Chimney's chimney with braces'",
    "'Local man shouting at birds to stop evading taxes' more at 9PM EST",
    "James Tooley caught doing donuts in stolen Tesla",
    "Computing Students stage protest as they are expected to do Computing Modules",
    "Tourists flock to Buckingham thinking it was Buckingham Palace",
    "The crown jewels were mistakingly rerouted to Buckingham instead of Buckingham Palace",
    "Local animals create union to deal with Swan attacks"
];
var currentPhraseIndex = Math.floor(Math.random() * phrases.length);
document.getElementById("marquee").innerHTML = phrases[currentPhraseIndex];

function updateMarquee() {
    currentPhraseIndex = Math.floor(Math.random() * phrases.length);
    document.getElementById("marquee").innerHTML = phrases[currentPhraseIndex];
}

function ToggleHalfPage() { //This opens & closes half page
    //console.log("Testing");
    var halfPage = document.getElementById("halfPage");
    halfPage.classList.toggle("open");
}

function WriteToHalfPageTitle(number) { //Writes the story's title into the half page
    //console.log("story #" + number);

    var paragraphSubject = document.getElementById("title #" + number);
    var paragraphTarget = document.getElementById("titleHolder");
    paragraphTarget.textContent = paragraphSubject.textContent;
}

function WriteToHalfPage(number) { //Writes the stories into the half page

    // Stories:
    var stories = [
        "Local man was forced to live in the White Hart after he posted a Yelp review saying that he didn't fancy the living conditions of the establishment. This sparked outrage as the community locked him inside and forced him to stay longer until he writes a better review.",
        "In an unexpected turn of events, alligators in Buckingham have gone on strike and are refusing to let humans use the river walkway. The reptilian workers are fed up with the lack of safety measures in place, and have decided to take matters into their own claws.",
        "The first thing you should never say to a computing student is; Number one: Can you fix my computer? It's making a weird noise, like 'beep boop'! Number two: You're a computer science student? So, you must know how to hack into anyone's Facebook, right? Number three: Oh, you're studying programming? Can you write a program that will do all my assignments for me? Number four: Computers are so easy, even my grandma can use them. What's the big deal? Number five: Why are you studying computer science? Aren't robots going to take over the world and steal your job? Number six: I have this great idea for an app. I'll tell you the concept, and you can do all the coding for me, deal? Number seven: Computing is just typing, right? Anyone can type! Number eight: I heard you're studying algorithms. Can you solve this math problem for me? It's been bugging me for days. Number nine: I bet you spend all your time playing video games instead of studying. Number ten: Computing is so boring. I don't know how you can enjoy it.",
        "In an age dominated by rapid advancements in Artificial Intelligence (AI), the notion of AI-generated news articles may appear tempting. However, we must approach the idea of complete automation in news writing with caution. While AI technology has demonstrated its potential in automating certain tasks, allowing AI to solely write news articles can have profound and alarming implications for society at large. This article unearths some compelling reasons why the unfettered reliance on AI in news reporting can lead to detrimental outcomes. The Erosion of Authenticity and Human Perspective: A cornerstone of news reporting lies in the human touch. Journalists bring their lived experiences, unique perspectives, and ethical standards to their work. Regrettably, AI lacks the intrinsic ability to truly comprehend and convey the depth of human emotions and perspectives crucial for engrossing storytelling. Consequently, news articles generated by AI risk becoming sterile and disconnected, failing to forge an empathetic bond with readers. Ethical Quandaries and Bias Amplification: AI systems learn from existing data, which can inadvertently perpetuate biases present in the training data. Should AI algorithms assume the role of news writers, there exists an inherent danger of biased reporting or unintentional reinforcement of stereotypes. This poses ethical concerns as it could fuel misinformation, deepen societal divisions, and undermine the very foundations of objective journalism. Limited Contextual Understanding and Analysis: News articles often require a comprehensive understanding of complex situations, nuanced analysis, and contextual knowledge. While AI algorithms excel in processing vast amounts of information, they struggle to grasp the intricate web of interconnected events, historical context, and sociopolitical nuances that shape news stories. Relying solely on AI-generated articles risks oversimplification, leading to a loss of depth and accuracy in reporting. Impersonal and Detached Reporting: AI-generated news articles lack the ability to provide a human touch, leaving readers with an impersonal and detached experience. News stories require empathy, compassion, and an innate understanding of the human condition to resonate with audiences. By relinquishing the human element, AI-written articles fail to capture the essence of human stories and deprive readers of the emotional connection that quality journalism fosters. Impact on Journalism Profession and Job Losses: The automation of news writing threatens the livelihoods of journalists. AI-generated articles could potentially replace human journalists, leading to significant job losses in the industry. This not only disrupts the profession but also jeopardizes the invaluable role that journalists play in holding power accountable, uncovering hidden truths, and serving as the voice of the people.While AI has made significant strides in various fields, relegating news writing entirely to AI systems presents an array of dangers. From the erosion of authenticity and human perspective to ethical dilemmas, the pitfalls are numerous. In an age where trusted journalism is more critical than ever, it is essential to preserve the human element in news reporting. Rather than replacing journalists, AI should be harnessed as a tool to augment their abilities, aiding in research, fact-checking, and data analysis. By embracing a collaborative approach, we can ensure that journalism remains a bastion of truth, integrity, and human connection in the face of technological advancements. Written by  -CHAD Grant Pelumina Tellnu",
        "Climate Change activists get lost after burning all of Buckingham's supply of maps",
        "Girl scouts gettin angie"
    ];

    //console.log(stories[number]);

    var paragraphTarget = document.getElementById("storyHolder"); // This is the storyHolder
    paragraphTarget.textContent = stories[number];
}

var fileUrls = [ //Working on makin it so we can make our own ads
    'Ads/Ad_1.html',
];

function openRandomPopup() {
    var randomIndex = Math.floor(Math.random() * fileUrls.length);
    var randomFileUrl = fileUrls[randomIndex];
    
    var width = 600;
    var height = 400;

    var screenWidth = screen.width;
    var screenHeight = screen.height;

    var randomLeft = Math.floor(Math.random() * (screenWidth - width));
    var randomTop = Math.floor(Math.random() * (screenHeight - height));

    var popupWindow = window.open(randomFileUrl, '_blank', 'width=' + width + ', height=' + height + ', left=' + randomLeft + ', top=' + randomTop);
}

//function to open login Popup
function openLogin(){
    document.getElementById("modal").style.display="block";
}

function closeLogin(){
    document.getElementById("modal").style.display="none";
}

// Call the function after a random delay
var randomDelay = Math.floor(Math.random() * 5000) + 1000; // time / 1k = time in seconds
setTimeout(openRandomPopup, randomDelay);

window.onload = function () {
// Replace 'YOUR_API_KEY' with the API key obtained from OpenWeatherMap
const apiKey = '7aa2af53dfb50efa5c75596671fd8b1b';

// Define the latitude and longitude coordinates for the location
const latitude = 51.9995;
const longitude = -0.9864;

// Define the URL for the current weather API endpoint
const apiUrl = `https://api.openweathermap.org/data/2.5/weather?lat=${latitude}&lon=${longitude}&appid=${apiKey}`;

//console.log(apiUrl);

// Calculate milliseconds in a year
const minute = 1000 * 60;
const hour = minute * 60;
const day = hour * 24;
const year = day * 365;

// Divide Time with a year
const date = new Date();

console.log((date.getMonth() + 1) + "/" + date.getDate() + "/" + (1970 + Math.round(date.getTime() / year)));

document.getElementById("Today").textContent = (date.getMonth() + 1) + "/" + date.getDate() + "/" + (1970 + Math.round(date.getTime() / year))

//GET time
axios.get(apiUrl)
    .then(response => {
    //Yay, weather info "https://openweathermap.org/current"
    const weatherData = response.data.weather[0];
    const temperatureInKelvin = response.data.main.temp;
    const temperatureInFahrenheit = Math.floor((temperatureInKelvin - 273.15) * 9/5 + 32);
    const windSpeedK = response.data.wind.speed;
    const city = response.data.name;

    // Display the weather report using console.log or update your HTML
    //console.log(`Weather in ${city}: ${weatherData.description}`);
    //console.log(`Temperature: ${temperatureInFahrenheit}°F`);

    //Change the tempature
    const weatherElement = document.getElementById('weather');
    weatherElement.textContent = ` ${temperatureInFahrenheit}\u00B0F, ${weatherData.description} in ${city}, ` + response.data.main.humidity + "% wet air";
    })
    .catch(error => {
    console.log('Error fetching weather data:', error);
    });
};

// This is for the background ---------------------------------------------------------------------------------------------------------------------------------------
// Ref : https://codepen.io/renanpupin/pen/RPmXdr

// Add an event listener to track scroll position
// Debounce function to limit the frequency of function execution
function debounce(func, delay) {
    let timer;
    return function() {
      clearTimeout(timer);
      timer = setTimeout(func, delay);
    };
  }
  

  // Function to handle scroll events
  function handleScroll() {
    var scrollPosition = window.pageYOffset || document.documentElement.scrollTop;
  
    console.log('Scroll position:', scrollPosition, 'px', '/', Math.floor((scrollPosition / window.innerHeight) * 106), '%');
  
    let color = (Math.floor((((scrollPosition / window.innerHeight) * 100))) + 10).toString(16);
    let color2 = (Math.floor((((scrollPosition / window.innerHeight) * 100))) + 82).toString(16)

    console.log(`#${color2}${color}FF`);
  
    document.body.style.backgroundColor = `#${color2}${color}FF`;
  }

  // Add a debounced event listener to track scroll position
  window.addEventListener('scroll', debounce(handleScroll, 1));
  
// This is for the live weather map -----------------------------------------------------------------------------------------------------------------

